### ISSUE TITLE
Creating keys fails with latest version

### ISSUE THREAD

**Issue by bsk0** [GoogleCloudPlatform/google-cloud-gemserver#37]
After successfully deploying the service and creating the cloud SQL instance, key generation fails with the error message: "Error generating key". No further information is available.

**Comment by alvaroinckot** [comment]
Same problem here

The results of  ` google-cloud-gemserver create-key`:

Internal Server Error

@boskonyc Have you solved this issue? Thanks.

**Comment by bsk0** [comment]
@alvarocantador We went a different route

**Comment by itsmechlark** [comment]
Same here. Any fix?

**Comment by itsmechlark** [comment]
Here's the log:
```
2018-08-02 07:10:42 default[20180802t143820]  [2018-08-02 07:10:42 +0000] - ERROR - 2018-08-02 07:10:42 - RuntimeError - Unauthorized:
2018-08-02 07:10:42 default[20180802t143820]  	/app/lib/google/cloud/gemserver/authentication.rb:119:in `appengine_version'
2018-08-02 07:10:42 default[20180802t143820]  	/app/lib/google/cloud/gemserver/authentication.rb:87:in `validate_token'
2018-08-02 07:10:42 default[20180802t143820]  	/app/lib/patched/web.rb:39:in `block (2 levels) in <top (required)>'
2018-08-02 07:10:42 default[20180802t143820]  	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `call'
2018-08-02 07:10:42 default[20180802t143820]  	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `block in compile!'
2018-08-02 07:10:42 default[20180802t143820]  	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
2018-08-02 07:10:42 default[20180802t143820]  	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:994:in `route_eval'
2018-08-02 07:10:42 default[20180802t143820]  	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
2018-08-02 07:10:42 default[20180802t143820]  	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1015:in `block in process_route'
2018-08-02 07:10:42 default[20180802t143820]  	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `catch'
2018-08-02 07:10:42 default[20180802t143820]  	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `process_route'
2018-08-02 07:10:42 default[20180802t143820]  	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:973:in `block in route!'
2018-08-02 07:10:42 default[20180802t143820]  	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `each'
2018-08-02 07:10:42 default[20180802t143820]  	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `route!'
2018-08-02 07:10:42 default[20180802t143820]  	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1085:in `block in dispatch!'
2018-08-02 07:10:42 default[20180802t143820]  	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'
2018-08-02 07:10:42 default[20180802t143820]  	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'
2018-08-02 07:10:42 default[20180802t143820]  	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'
2018-08-02 07:10:42 default[20180802t143820]  	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `block in call!'
2018-08-02 07:10:42 default[20180802t143820]  	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'
2018-08-02 07:10:42 default[20180802t143820]  	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'
2018-08-02 07:10:42 default[20180802t143820]  	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'
2018-08-02 07:10:42 default[20180802t143820]  	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `call!'
2018-08-02 07:10:42 default[20180802t143820]  	/app/vendor/bundle/ruby/2.3.0/gems/rack-protection-1.5.5/lib/rack/protection/xss_header.rb:18:in `call'
2018-08-02 07:10:42 default[20180802t143820]  	/app/vendor/bundle/ruby/2.3.0/gems/rack-protection-1.5.5/lib/rack/protection/path_traversal.rb:16:in `call'
2018-08-02 07:10:42 default[20180802t143820]  	/app/vendor/bundle/ruby/2.3.0/gems/rack-protection-1.5.5/lib/rack/protection/json_csrf.rb:18:in `call'
2018-08-02 07:10:42 default[20180802t143820]  	/app/vendor/bundle/ruby/2.3.0/gems/rack-protection-1.5.5/lib/rack/protection/base.rb:49:in `call'
2018-08-02 07:10:42 default[20180802t143820]  	/app/vendor/bundle/ruby/2.3.0/gems/rack-protection-1.5.5/lib/rack/protection/base.rb:49:in `call'
2018-08-02 07:10:42 default[20180802t143820]  	/app/vendor/bundle/ruby/2.3.0/gems/rack-protection-1.5.5/lib/rack/protection/frame_options.rb:31:in `call'
2018-08-02 07:10:42 default[20180802t143820]  	/app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.10/lib/rack/nulllogger.rb:9:in `call'
2018-08-02 07:10:42 default[20180802t143820]  	/app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.10/lib/rack/head.rb:13:in `call'
2018-08-02 07:10:42 default[20180802t143820]  	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:182:in `call'
2018-08-02 07:10:42 default[20180802t143820]  	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:2013:in `call'
2018-08-02 07:10:42 default[20180802t143820]  	/app/vendor/bundle/ruby/2.3.0/gems/server_health_check-rack-0.1.0/lib/server_health_check_rack/middleware.rb:12:in `call'
2018-08-02 07:10:42 default[20180802t143820]  	/app/vendor/bundle/ruby/2.3.0/bundler/gems/gemstash-a5a78e2a771a/lib/gemstash/gem_source/rack_middleware.rb:18:in `call'
2018-08-02 07:10:42 default[20180802t143820]  	/app/vendor/bundle/ruby/2.3.0/bundler/gems/gemstash-a5a78e2a771a/lib/gemstash/env.rb:35:in `call'
2018-08-02 07:10:42 default[20180802t143820]  	/app/vendor/bundle/ruby/2.3.0/bundler/gems/gemstash-a5a78e2a771a/lib/gemstash/logging.rb:56:in `call'
2018-08-02 07:10:42 default[20180802t143820]  	/app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.10/lib/rack/deflater.rb:35:in `call'
2018-08-02 07:10:42 default[20180802t143820]  	/app/vendor/bundle/ruby/2.3.0/gems/puma-2.16.0/lib/puma/configuration.rb:81:in `call'
2018-08-02 07:10:42 default[20180802t143820]  	/app/vendor/bundle/ruby/2.3.0/gems/puma-2.16.0/lib/puma/server.rb:557:in `handle_request'
2018-08-02 07:10:42 default[20180802t143820]  	/app/vendor/bundle/ruby/2.3.0/gems/puma-2.16.0/lib/puma/server.rb:404:in `process_client'
2018-08-02 07:10:42 default[20180802t143820]  	/app/vendor/bundle/ruby/2.3.0/gems/puma-2.16.0/lib/puma/server.rb:270:in `block in run'
2018-08-02 07:10:42 default[20180802t143820]  	/app/vendor/bundle/ruby/2.3.0/gems/puma-2.16.0/lib/puma/thread_pool.rb:106:in `block in spawn_thread'
```

**Comment by jernestosuarez** [comment]
The same problem here, following the instructions the google-cloud-gemserver create fails with:
`
 Would you like to setup a default key? [Y/n] (default yes)
 Y
 Error generating key
`

And with the  google-cloud-gemserver create-key returns:

`<h1>Internal Server Error</h1>`
`Note: remember to add this key to ~/.gem/credentials so that you are able to push gems to the gemserver.
Note: remember to add this key to your bundle config so that 'bundle install' works for private gems (bundle config http://my-gemserver.appspot.com/private/ my-key'
`
