### ISSUE TITLE
Crash when setting up default key during create

### ISSUE THREAD

**Issue by dazuma** [GoogleCloudPlatform/google-cloud-gemserver#6]
Excerpt from running `google-cloud-gemserver create` on a new project.

```
Saving configuration
Would you like to setup a default key? [Y/n] (default yes)

/usr/local/google/home/dazuma/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/google-cloud-gemserver-0.1.0/lib/google/cloud/gemserver/cli/server.rb:167:in `extract_key': undefined method `+' for nil:NilClass (NoMethodError)
        from /usr/local/google/home/dazuma/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/google-cloud-gemserver-0.1.0/lib/google/cloud/gemserver/cli/server.rb:107:in `setup_default_keys'
        from /usr/local/google/home/dazuma/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/google-cloud-gemserver-0.1.0/lib/google/cloud/gemserver/cli/server.rb:73:in `deploy'
        from /usr/local/google/home/dazuma/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/google-cloud-gemserver-0.1.0/lib/google/cloud/gemserver/cli.rb:68:in `create'
        from /usr/local/google/home/dazuma/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
        from /usr/local/google/home/dazuma/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
        from /usr/local/google/home/dazuma/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
        from /usr/local/google/home/dazuma/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
        from /usr/local/google/home/dazuma/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/google-cloud-gemserver-0.1.0/lib/google/cloud/gemserver/cli.rb:43:in `start'
        from /usr/local/google/home/dazuma/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/google-cloud-gemserver-0.1.0/bin/google-cloud-gemserver:5:in `<top (required)>'
        from /usr/local/google/home/dazuma/.rbenv/versions/2.4.1/bin/google-cloud-gemserver:22:in `load'
        from /usr/local/google/home/dazuma/.rbenv/versions/2.4.1/bin/google-cloud-gemserver:22:in `<main>'
```

**Comment by arhamahmed** [comment]
What is the version of gcloud you have installed?

**Comment by arhamahmed** [comment]
What is the output of `./bin/google-cloud-gemserver create_key`? If the output includes "Internal server error" then something went wrong with the deploy and this will fail.

**Comment by dazuma** [comment]
It does say Internal Server Error.

The app does seem to be running at some level, though. I can hit the root (which redirects to rubygems.org).

**Comment by arhamahmed** [comment]
The error originates from [here](https://github.com/bundler/gemstash/blob/a5a78e2a771abde965cff0be84d5cbcc5e1a93b8/lib/gemstash/env.rb#L141). It has happened before, but it isn't consistent. I am not sure exactly what causes migrations to occasionally fail.
